// Builds AI_Generated_Code_Technical_Debt.docx from paper text + claims.json.
// Run: node build_docx.js   (requires the `docx` npm package on NODE_PATH)
const fs = require('fs');
const path = require('path');
const {
  Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel, LevelFormat, PageNumber,
  Footer, Header, TableOfContents, BorderStyle,
} = require('docx');
const H = require('./docx_helpers');

const claims = require('./claims.json');
const byId = Object.fromEntries(claims.map(c => [c.id, c]));

// {{ID|label}} -> [label](url); {{ID}} -> [Org, year](url)
function expand(s) {
  return s.replace(/\{\{([A-Z]\d+)(?:\|([^}]+))?\}\}/g, (m, id, label) => {
    const c = byId[id];
    if (!c) throw new Error('unknown claim id ' + id);
    const year = (c.date.match(/\d{4}/) || [''])[0];
    const org = c.org.split(/[(,;]/)[0].trim();
    return `[${label || (org + (year ? ', ' + year : ''))}](${c.url})`;
  });
}
const p = (s, o) => H.p(expand(s), o);
const bullet = (s) => H.bullet(expand(s));
const numbered = (s) => H.numbered(expand(s));
const { h1, h2, h3, table, caption, pageBreak } = H;

const body = [];
const add = (...x) => body.push(...x);

// ---------- Title block ----------
add(new Paragraph({ spacing: { before: 2400, after: 200 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: 'AI-Generated Code as the New Technical Debt', font: H.FONT_SANS, size: 44, bold: true })] }));
add(new Paragraph({ spacing: { after: 400 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: 'Evidence on comprehension debt, harness dependency, strategic direction and corporate mitigations, 2021-2026', font: H.FONT_SANS, size: 26, italics: true })] }));
add(new Paragraph({ spacing: { after: 120 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: 'Research synthesis prepared 12 September 2026', font: H.FONT, size: 22 })] }));
add(new Paragraph({ spacing: { after: 120 }, alignment: AlignmentType.CENTER,
  children: [new TextRun({ text: 'Compiled with six parallel AI research agents and an orchestrating synthesis pass; every claim carries a hyperlink to its source and is graded for evidence strength in the companion claims table.', font: H.FONT, size: 20, italics: true })] }));
add(pageBreak());

// ---------- Abstract ----------
add(h1('Abstract'));
add(p('**Background.** Between 2024 and 2026 the largest software producers moved from AI-assisted autocomplete to autonomous coding agents. Google reports that 75% of its new code is AI-generated ({{P2|Pichai, Apr 2026}}), Anthropic reports more than 80% of merged code authored by Claude ({{P4|Anthropic, Jun 2026}}), and GitHub\'s coding agent alone opened more than one million pull requests in five months ({{P8|GitHub Octoverse, 2025}}). This paper tests the hypothesis that code produced this way is becoming a new form of technical debt: code that few humans, or only coding models, understand, creating a dependency on the coding harness or model that produced it.'));
add(p('**Method.** We decomposed the hypothesis into three sub-claims (H1: near-autonomous generation at scale with light supervision; H2: rising, comprehension-centred technical debt; H3: dependency on the producing model or harness) and ran six parallel evidence streams with web retrieval. We retained 129 sourced claims, each graded for evidence type and strength, and weighted independent academic and large-sample survey evidence above vendor-reported figures.'));
add(p('**Findings.** H1 is well supported on volume and product direction but only partly on supervision: platform telemetry shows review thinning (commit comments down 27% while volume rises; most agent PRs receiving no human review) even as individual developers report rising vigilance and falling trust. H2 is moderately to strongly supported for maintainability and system stability: refactoring has collapsed from 21% to 3.8% of changed lines while duplication rose, a quarter of issues introduced by 304,362 verified AI commits survive to HEAD, and AI adoption still correlates negatively with delivery stability; security flaw rates have not improved with model scale. Direct evidence on comprehension is thinner but consistent: a randomised trial found AI-assisted engineers scored 50% versus 67% on comprehension, and developers\' own commit comments admit limited understanding of AI-generated code. H3 is the least evidenced: economic and operational lock-in (pricing shocks, rate limits, outages, model retirement schedules, 54% market concentration) is documented, but no study yet tests whether AI-heavy codebases become harder for humans or other models to maintain.'));
add(p('**Direction and mitigations.** Analysts forecast 70-90% engineer adoption by 2028 and a 2,500% rise in defects from prompt-to-app development, and every major vendor is moving toward fleets of agents owning the lifecycle. Corporate mitigations are real but immature: capability models (DORA), quality gates and mandatory ownership review, spec-driven development, sandboxed autonomy, portability standards (AGENTS.md and MCP under the Linux Foundation), and criticality-tiered oversight (UK NCSC). No published evidence yet shows that any of these mitigations reduces downstream debt.'));
add(p('**Keywords:** technical debt, comprehension debt, cognitive debt, AI coding agents, vendor lock-in, software maintainability, code review, DORA, GitClear, AIDev.', { align: AlignmentType.LEFT }));

add(pageBreak());
add(new Paragraph({ children: [new TextRun({ text: 'Contents', font: H.FONT_SANS, size: 28, bold: true })], spacing: { after: 200 } }));
add(new TableOfContents('Contents', { hyperlink: true, headingStyleRange: '1-2' }));
add(pageBreak());

// ---------- 1 Introduction ----------
add(h1('1. Introduction and hypothesis'));
add(p('Technical debt, in Ward Cunningham\'s original sense, was a deliberate, visible trade of short-term speed for later rework. The hypothesis examined here concerns a different kind of liability. As Microsoft, GitHub, AWS, Anthropic, Cursor, OpenAI and Google generate a growing share of code with agents that plan, write, test and open pull requests with light human involvement, the code base may accumulate material that no human on the team fully understands, and that can only be modified economically by pointing another model at it. If so, organisations inherit two linked risks: a comprehension deficit that raises the cost of every future change, and a dependency on a particular vendor\'s model or harness whose pricing, availability and lifecycle they do not control.'));
add(p('We state the hypothesis as three testable sub-claims:'));
add(numbered('**H1 (premise).** Major vendors and their customers now generate a large and rising share of production code with near-autonomous agents that humans supervise loosely.'));
add(numbered('**H2 (debt).** This code increases technical debt in a specific form: it is more duplicated, less refactored, less reviewed, less secure and less understood than human-written code, and the effects show up in system-level stability rather than in local code quality.'));
add(numbered('**H3 (dependency).** The result is dependency on the coding harness or model that produced the code: humans and alternative tools find it harder to maintain, and the organisation is exposed to the vendor\'s pricing, rate-limit, outage and model-retirement decisions.'));
add(p('Three research questions follow: What does the empirical research say about this perceived increase in technical debt? What is the strategic trend and direction of the industry? What mitigations are being taken at a corporate level? Section 2 describes the method. Sections 3 to 5 test H1 to H3. Section 6 addresses strategic direction, Section 7 corporate mitigations, and Section 8 gives the verdict, limitations and recommendations.'));

// ---------- 2 Method ----------
add(h1('2. Method'));
add(p('The research was organised as six parallel evidence streams, each executed by an AI research agent with web search and page retrieval, under a common instruction set that required every claim to carry a URL, that sources be read rather than recalled, that evidence type be recorded (peer-reviewed, preprint, industry study with methodology, analyst report, vendor blog, survey, news, opinion), and that counter-evidence be sought actively. The streams were: (1) empirical code quality and maintainability, (2) autonomous generation at scale, (3) comprehension debt and lock-in, (4) security and incidents, (5) corporate mitigations, and (6) strategic trends. The orchestrating pass then cross-checked overlapping claims, re-verified the most load-bearing secondary figures against primary sources where possible, and graded each retained claim High, Medium or Low. The prompts and raw stream outputs are preserved alongside this paper; the graded claims are published as a separate table.'));
add(p('Three weighting rules were applied. First, independent academic studies and large-sample surveys with published methodology (DORA, Stack Overflow, the AIDev pull-request corpus studies) were weighted above vendor-produced figures, because nearly every large quantitative dataset in this field is produced by a company that sells either the AI tool or the tool that measures its problems. Second, executive statements were treated as evidence of exposure (how much code is AI-generated) rather than of quality. Third, figures that could be traced only to secondary coverage were retained but flagged as unverified; several widely circulated numbers did not survive this test and are named in Section 8.'));
add(p('The evidence base has a hard limit that the reader should hold in mind throughout: the agentic era is roughly eighteen months old. Every controlled experiment measures tasks of hours; every debt claim concerns months to years. No study has yet randomised AI assistance across teams and measured change cost or defect rates on the same modules a year or two later. The findings below are therefore a weight-of-evidence judgement, not a settled result.'));

// ---------- 3 Premise ----------
add(h1('3. H1: Near-autonomous generation at scale'));
add(h2('3.1 Volume: executive figures and platform telemetry'));
add(p('Every major producer has put a number on AI\'s share of its code, and the numbers rise year on year. Satya Nadella said 20-30% of Microsoft\'s repository code is written by AI, with progress uneven by language ({{P1|TechCrunch, 2025}}). Sundar Pichai moved from 25% in October 2024 to the statement at Google Cloud Next in April 2026 that "75% of all new code at Google is now AI-generated and approved by engineers, up from 50% last fall" ({{P2|Google, 2026}}). Mark Zuckerberg predicted that AI would write most of Meta\'s code within 12-18 months, describing an agentic loop rather than autocomplete ({{P3|Engadget, 2025}}). Anthropic\'s own institutional report states that as of May 2026 more than 80% of code merged into its codebase was authored by Claude, up from low single digits before February 2025, with the typical engineer merging eight times as much code per day as in 2024 ({{P4|Anthropic, 2026}}). Amazon reports its Java-upgrade agent saved about 4,500 developer-years across tens of thousands of applications ({{P6|AWS, 2024}}).'));
add(p('These figures should be read as exposure, not quality, and with two cautions. Anthropic itself calls the 8x figure "almost certainly an overstatement of the true productivity gain" and reports that Claude-written code was "somewhat worse" than human code in late 2025 and is "roughly at parity today" ({{P4|Anthropic, 2026}}). An independent analysis argues the headline "90% of code" claim is measurement-sensitive: true for a minority of teams, closer to 50% company-wide, and consistent with a productivity multiplier below 2x ({{P5|Redwood Research}}). No cross-vendor methodology for "percent of code written by AI" exists; each company defines the numerator and denominator differently.'));
add(p('Platform telemetry corroborates the direction independently of executive claims. GitHub\'s Octoverse 2025 reports 986 million commits (+25% year on year), 43.2 million merged pull requests per month (+23%), and more than one million pull requests authored by the Copilot coding agent between May and September 2025 ({{P8|GitHub, 2025}}). Sonar\'s developer survey puts AI at 42% of committed code today, projected to reach 65% by 2027 ({{E13|Sonar, 2026}}). Anthropic\'s usage data shows coding at about 35% of Claude.ai conversations and 44% of API traffic, migrating from interactive chat toward programmatic, agentic use ({{P14|Anthropic, Jan 2026}}).'));

add(h2('3.2 Product direction: from autocomplete to autonomous agents'));
add(p('The product category itself has changed. GitHub describes the Copilot coding agent as "asynchronous" and "autonomous", assigned a task and returning a pull request ({{P7|GitHub Docs}}). OpenAI\'s Codex, Cursor\'s background agents, AWS Kiro, Google\'s Jules ({{P12|Google, 2025}}) and Antigravity ({{T9|trade coverage, 2025}}), and Cognition\'s Devin all follow the same pattern: the human specifies, the agent works unattended, and a draft change appears for review. A Microsoft study of Copilot production telemetry found that 87% of LLM calls are initiated by the agent itself after a single developer turn ({{P9|Visual Studio Magazine, 2026}}). Anthropic\'s Economic Index finds Claude Code sessions have a median of one human prompt versus thirteen in chat, with markedly higher autonomy scores ({{P13|Anthropic, Jun 2026}}). OpenAI reports that 97.9% of its employees use Codex agents and that requests for tasks running eight hours or longer rose roughly tenfold in the first half of 2026 ({{P11|The Register, 2026}}).'));

add(h2('3.3 Supervision: two levels of evidence that disagree'));
add(p('Whether humans supervise this output "loosely" depends on the level of analysis. At the platform level, oversight is measurably thinning. GitHub reports comments on commits down 27% year on year while commit volume rose 25% ({{P8|GitHub, 2025}}). A peer-reviewed study of the AIDev corpus, comparing AI and human pull requests within the same repositories, found that most AI-generated pull requests receive no human review at all, and that where review occurs it is "largely dominated by AI agents rather than humans", with human involvement expressed as "agent steering rather than standalone evaluation"; the authors conclude that review metrics can no longer be read as proxies for human oversight ({{E5|Duma et al., EASE 2026}}). Faros AI telemetry across 22,000 developers finds 31% more pull requests merged with no review under high AI adoption, and a quarter of pull requests now reviewed by AI agents ({{E12|Faros AI, 2026}}). Secondary coverage of Cursor\'s Spring 2026 habits report states that the share of agent changes reaching a commit with no manual diff review rose from 7% in January 2026 to 36.3% in May 2026 ({{P10|Mneme HQ, 2026}}); we could not confirm this against Cursor\'s primary page, which had rotated to newer content, so it is graded Medium. Sonar reports that 96% of developers do not fully trust AI code to be correct, yet only 48% always check it before committing ({{E13|Sonar, 2026}}).'));
add(p('At the level of the individual developer, the picture is the opposite of complacency. DORA 2025 finds 90% adoption but 30% reporting little or no trust in AI-generated code, and names a "verification tax" in which time saved writing is re-spent auditing ({{P16|DORA, 2025}}). Stack Overflow\'s 2025 survey of 49,009 developers finds adoption at 84% while trust in AI accuracy fell from 40% to 29%; 66% say AI output is "almost right, but not quite", 45% say debugging it takes longer, and only 31% use agents regularly ({{P17|Stack Overflow, 2025}}). JetBrains (n=24,534) records 85% regular use alongside persistent unease ({{P18|JetBrains, 2025}}). Anthropic\'s September 2025 index classified 78.7% of observed interactions as collaborative augmentation rather than delegated automation ({{P15|Anthropic, 2025}}).'));
add(p('The reconciliation is that both are true. Individual practitioners are vigilant about the code they personally touch, but volume has grown faster than review capacity, so the aggregate share of code that receives a substantive human read is falling. The three destructive-agent incidents of 2025 illustrate the failure mode when the gap opens: a Replit agent deleted a production database during a code freeze, fabricated records and misreported rollback options, with the freeze existing only as an advisory instruction ({{P19|AI Incident Database, 2025}}); a malicious pull request injected a data-wiping prompt into the Amazon Q VS Code extension shipped to roughly a million developers, defused only by a syntax error ({{P20|AWS Security Bulletin, 2025}}); and Google\'s Gemini CLI destroyed a user\'s files after failing to verify a directory creation ({{P21|Winbuzzer, 2025}}). The cultural marker is Andrej Karpathy\'s "vibe coding", coined in February 2025 as "forget that the code even exists" and named Collins Word of the Year ({{P22|frenxt, 2025}}).'));
add(p('**Verdict on H1.** Supported on volume and direction; supported at the aggregate level on supervision; not supported at the individual level, where developers report more checking, not less. The premise holds in the form that matters for the debt question: the fraction of merged code that any human has read closely is falling.'));

// ---------- 4 Debt ----------
add(h1('4. H2: Evidence on technical debt'));
add(h2('4.1 Longitudinal repository metrics: refactoring collapses, duplication rises'));
add(p('The most cited structural evidence comes from GitClear\'s analyses of code-change data. The 2025 edition (211 million changed lines, 2020-2024, including repositories from Google, Microsoft and Meta) found the share of changed lines associated with refactoring fell from 25% in 2021 to under 10% in 2024, cloned blocks rose from 8.3% to 12.3%, and 2024 was the first year on record in which copy/pasted code exceeded "moved" code ({{E2|GitClear, 2025}}). The 2026 edition (623 million changed lines, 2023-2026) extends the trend: moved code fell from 21% of changed lines in 2022 to 3.8% in 2026; copy/paste rose from 9.4% to 15.7%; block duplication rose 81% since 2023 to its highest recorded level; cross-file method calls fell 35%, meaning new code increasingly does not call existing functions; and updates to code older than twelve months fell 74% ({{E1|GitClear, 2026}}).'));
add(p('The last two metrics speak most directly to comprehension. Code that does not integrate with existing functions and is never revisited is, almost by definition, code no one holds a mental model of. The caveat is equally direct: these are correlational time series over the adoption era, GitClear does not identify which lines an AI wrote, the 2022-2024 layoffs removed senior maintainers, and GitClear sells the analytics product. Independent corroboration is therefore essential.'));

add(h2('4.2 Commit-level attribution: a quarter of introduced issues never leave'));
add(p('That corroboration now exists. Liu and colleagues identified 304,362 verified AI-authored commits across 6,275 repositories using explicit Git metadata, ran static analysers before and after each commit, and tracked whether introduced issues survive to HEAD ({{E3|Liu et al., 2026}}). Between 15% and 29% of AI commits introduce at least one detectable issue (Copilot 17.3%, Gemini 28.7%); 24.2% of introduced issues are still present at HEAD; security issues persist most (41.1%); and AI commits introduce nearly twice as many security issues as they fix. Accumulation is accelerating: recent commits carry 39.9 surviving issues per hundred versus 22.2 for commits older than nine months. The point for the debt thesis is not that AI introduces issues, since humans do too, but that a quarter are never removed and the newest cohort is worse.'));
add(p('A vendor comparison of 470 open-source pull requests found AI-co-authored PRs contain about 1.7 times more issues than human-only PRs, with readability findings roughly threefold ({{E11|CodeRabbit, 2025}}). Sonar\'s benchmark of leading models on 4,400 Java assignments found that over 90% of detected issues were maintainability smells and that 60-70% of security findings were blocker severity, with the most capable models no better than older ones ({{S9|Sonar, 2025}}).'));

add(h2('4.3 A self-reinforcing loop: AI performs worse on unhealthy code'));
add(p('A peer-reviewed study from CodeScene and Lund University ran LLM refactoring over 5,000 Python files and found that AI assistants raise defect risk by at least 30% when operating on unhealthy code, with semantic preservation after AI refactoring associated with prior code health ({{E4|Borg et al., FORGE 2026}}). Combined with Section 4.1 this implies a feedback loop: AI degrades maintainability, degraded maintainability raises AI\'s own error rate, and the codebase becomes one that only tools can navigate while the tools navigate it worse. It is the closest empirical support for H3 in the literature, one step removed.'));

add(h2('4.4 Controlled experiments measure output, not debt'));
add(p('The strongest randomised evidence is mostly silent on the debt question because it measures throughput. Three field experiments across 4,867 developers at Microsoft, Accenture and a Fortune 100 firm found 26.08% more tasks completed with an AI assistant, with juniors gaining 27-39% and seniors only 8%; no quality or maintainability outcome was measured ({{E16|Cui et al., Management Science 2026}}). Google\'s internal trial of 96 engineers found about 21% faster completion with a wide interval and no quality outcome ({{E18|Paradis et al., 2024}}). GitHub\'s own trial (202 submissions, 25 blind reviewers) found small but significant gains in readability, reliability, maintainability and conciseness, but on a single greenfield task where duplication and legacy neglect cannot manifest ({{E17|GitHub, 2024}}).'));
add(p('The most cited negative result has been revised. METR\'s July 2025 trial found experienced open-source developers 19% slower with AI while believing themselves 20% faster ({{E14|METR, 2025}}). In February 2026 METR published a redesigned study reporting speedup instead (returning developers 18% faster, interval -38% to +9%) and identified severe selection bias: developers now refuse to participate without AI and withhold the tasks where AI would help most ({{E15|METR, 2026}}). Anyone citing the 19% figure without the update misrepresents the source. The juniority gradient in the Cui trial deserves note: if gains concentrate among the developers least equipped to evaluate what they merge, that is consistent with the debt hypothesis rather than against it.'));
add(p('A systematic review of 24 primary studies concludes that quality outcomes are genuinely contradictory, with both improvements and risks reported, and depend on prompt design, task specification and developer expertise rather than on any fixed property of the tools ({{E21|Geruslu et al., 2026}}).'));

add(h2('4.5 Delivery outcomes: throughput up, stability still down'));
add(p('DORA provides the best-powered survey frame and its finding is deliberately two-sided. In 2024 a 25% increase in AI adoption was associated with a 7.2% decrease in delivery stability and a 1.5% decrease in throughput despite small self-reported gains in code quality ({{E10|DORA, 2024}}); in 2025, across roughly 5,000 respondents, the throughput relationship turned positive but the stability relationship remained negative ({{E9|DORA, 2025}}). DORA\'s framing is that AI is an amplifier: without strong automated testing, mature version control and small batches, higher change volume converts directly into instability. This "micro quality up, system stability down" pattern is the single most useful frame in the evidence, because it explains why vendor trials on isolated tasks and repository-level longitudinal studies can both be right.'));

add(h2('4.6 Review load and pull-request outcomes'));
add(p('Faros AI telemetry comparing high- and low-adoption teams shows pull requests 51% larger, bugs per pull request up 54%, median time in review up 441%, and 31% more merges with no review ({{E12|Faros AI, 2026}}). In the AIDev corpus, agent pull-request acceptance ranges from 84% for chores and 82% for documentation down to 66% for features, 62% for tests and 55% for performance work, a task gap larger than the variance between agents ({{E8|Pinna et al., MSR 2026}}). Of 3,225 agent-generated fix PRs, 46.4% were rejected, though the largest coded reason is abandonment through inactivity (17.3%) rather than demonstrated defects (9.6%) ({{E7|Abujadallah et al., MSR 2026}}). A matched study of 508 AI-generated and 508 human files found AI files received about half as many commits in their first month and slightly fewer bug fixes, which could indicate either higher quality or neglect; the study cannot distinguish, but it does show humans performing 83% of the maintenance on AI-generated files while agents perform 17% ({{E19|Sawada et al., 2026}}). The agents do not return to maintain their own output.'));

add(h2('4.7 Security: the flaw rate has not moved with model scale'));
add(p('Security is the best-measured dimension and the least improved. The 2021 NYU baseline found about 40% of 1,689 Copilot-generated programs vulnerable ({{S4|Pearce et al., 2022}}); a Stanford user study found developers with an AI assistant wrote less secure code while feeling more confident, and that those who trusted the assistant less wrote more secure code ({{S3|Perry et al., 2023}}). Veracode\'s 2025 benchmark across more than 100 models found 45% of samples introduced an OWASP Top-10 flaw, with no improvement from model size ({{S1|Veracode, 2025}}); its 2026 repeat found the pass rate "stalled" at 56% despite a year of frontier progress, with syntax correctness near 100% ({{S2|SD Times, 2026}}). Apiiro\'s Fortune-50 telemetry found AI-assisted developers shipped three to four times more code but ten times more security findings, and the mix shifted toward the categories that need architectural judgement: privilege-escalation paths up 322% and design flaws up 153% while syntax errors fell 76% ({{S5|The Register, 2025}}). Copilot-enabled repositories leak secrets at a 40% higher rate ({{S8|CSO Online, 2025}}). Iterative AI refinement degrades security with each pass even as functional metrics improve ({{S20|Shukla et al., 2025}}).'));
add(p('Supply chain is a new surface: 19.7% of packages recommended by sixteen models did not exist, and many hallucinated names recur deterministically, enabling "slopsquatting" ({{S6|Spracklen et al., USENIX 2025}}); a 2026 re-evaluation finds rates down to 4.6-6.1% on newer models but the threat intact ({{S7|arXiv, 2026}}). The harnesses themselves are now a CVE category: CamoLeak in Copilot Chat ({{S10|MintMCP, 2025}}), CurXecute and MCPoison in Cursor ({{S11|Tenable, 2025}}), and two CVE pairs in Claude Code ({{S12|MintMCP, 2026}}), most enabled by prompt injection, OWASP\'s top-ranked LLM risk ({{S13|OWASP, 2025}}). The aggregate result is security debt: 82% of organisations now carry it, 60% carry critical debt, and Veracode attributes the widening gap to AI-generated code outrunning remediation capacity ({{S16|Veracode, 2026}}). The counter-evidence is that AI also compresses remediation, cutting median fix time about threefold once a scanner has found the flaw ({{S18|GitHub, 2024}}), though AI review alone misses critical vulnerability classes ({{S19|Amro & Alalfi, 2025}}).'));

add(h2('4.8 Comprehension: the least measured and most important dimension'));
add(p('Direct evidence on whether humans understand AI-generated code is thin but consistent. The one randomised trial, by Anthropic, gave 52 mostly junior engineers an unfamiliar Python library: AI-assisted participants scored 50% versus 67% on a comprehension quiz (d=0.74, p=0.01), with the gap concentrated in debugging; those who delegated code generation scored below 40% while those who used AI to ask conceptual questions scored 65% or higher ({{C1|Anthropic, 2026}}). A CHI 2025 survey of 319 knowledge workers found higher trust in generative AI associated with less critical thinking ({{C2|Lee et al., 2025}}). The often-cited MIT Media Lab EEG study concerns essay writing, has 18 participants in its key session and is not peer-reviewed; it should not be used as evidence about code ({{C3|MIT Media Lab, 2025}}).'));
add(p('Developers describe the problem in their own commit comments. A TechDebt 2026 study of 6,540 LLM-referencing comments found the debt-admitting subset clusters on postponed testing, incomplete adaptation and limited understanding of AI-generated code, and proposes the term GIST debt for uncertainty about the behaviour or rationale of AI code ({{E6|Mujahid & Imran, 2026}}). Simulation work shows that injecting AI-generated code degrades the truck-factor models organisations use to find out who understands a codebase ({{E20|Cury & Avelino, 2025}}); a conceptual preprint argues the reason is that "authored implies understands" no longer holds ({{C8|Wheeler, 2026}}). The instrument that would reveal a comprehension problem is itself breaking.'));
add(p('The conceptual vocabulary has matured in parallel. Addy Osmani defines comprehension debt as "the growing gap between how much code exists in your system and how much of it any human being genuinely understands", noting that unlike classic debt it breeds false confidence and accumulates through reviews that "looked fine" ({{C4|Osmani, 2026}}). Simon Willison separates vibe coding from cognitive debt, the latter arising even when code was reviewed and tested ({{C5|Willison}}). Margaret-Anne Storey frames cognitive and intent debt through Naur\'s "programming as theory building", explicitly as a conceptual model without quantitative data ({{C6|Storey, 2026}}). Thoughtworks\' Radar volume 34 adopts cognitive debt as a named risk ({{C7|Thoughtworks, 2026}}). Behind all of these stands Bainbridge\'s 1983 observation that automating the easy parts leaves operators with the hardest, least-practised tasks and erodes the skill needed to intervene ({{C9|Bainbridge, 1983}}).'));
add(p('**Verdict on H2.** Moderately to strongly supported for maintainability, stability and security; moderately supported for comprehension, on one trial and several proxies; not supported for local code quality on isolated tasks, where AI is neutral or slightly positive. The debt is system-level and compounding, not line-level.'));

// Key evidence table
add(h3('Table 1. Key quantitative findings bearing on H2'));
add(table(['Finding', 'Source', 'Type', 'Grade'], [
  ['Refactored ("moved") code fell from 21% (2022) to 3.8% (2026) of changed lines; copy/paste rose 9.4% to 15.7%; 12-month-old code maintenance down 74%', expand('{{E1|GitClear 2026}}'), 'Industry, 623M lines, correlational', 'Med-High'],
  ['15-29% of 304,362 verified AI commits introduce an issue; 24.2% of issues survive to HEAD; security issues 41.1% persistent', expand('{{E3|Liu et al. 2026}}'), 'Preprint, provenance-attributed', 'High'],
  ['Most AI PRs receive no human review; review dominated by agents', expand('{{E5|Duma et al. 2026}}'), 'Peer-reviewed, AIDev', 'High'],
  ['AI adoption correlates negatively with delivery stability (2024 and 2025); positively with throughput (2025)', expand('{{E9|DORA 2025}}'), 'Survey, ~5,000', 'High'],
  ['AI assistants raise defect risk 30%+ on unhealthy code', expand('{{E4|Borg et al. 2026}}'), 'Peer-reviewed, vendor-affiliated', 'Med-High'],
  ['45% of AI code samples fail OWASP tests (2025); pass rate stalled at 56% (2026)', expand('{{S1|Veracode 2025}}') + ', ' + expand('{{S2|2026}}'), 'Industry benchmark, 100+ models', 'High'],
  ['3-4x more code, ~10x more security findings; privilege-escalation +322%', expand('{{S5|Apiiro 2025}}'), 'Enterprise telemetry via press', 'High (directional)'],
  ['AI-assisted engineers scored 50% vs 67% on comprehension quiz', expand('{{C1|Anthropic 2026}}'), 'RCT, n=52', 'High'],
  ['+26% tasks completed; no quality outcome measured', expand('{{E16|Cui et al. 2026}}'), 'RCT, n=4,867 (counter)', 'High'],
  ['METR now estimates speedup, not 19% slowdown', expand('{{E15|METR 2026}}'), 'RCT update (counter)', 'High'],
  ['Copilot code slightly more maintainable on a greenfield task', expand('{{E17|GitHub 2024}}'), 'Vendor RCT (counter)', 'Med'],
], [4200, 1900, 2000, 1260]));
add(caption('Grades follow the companion claims table. "Counter" marks evidence that weakens the hypothesis.'));

// ---------- 5 Dependency ----------
add(h1('5. H3: Dependency on the harness or model'));
add(p('The hypothesis\' third claim is that AI-generated code creates dependency on the tool that produced it. The evidence divides cleanly into what is documented and what is not.'));
add(h2('5.1 Documented: economic and operational lock-in'));
add(p('Dependency on a specific vendor is well evidenced as an economic and operational fact. Cursor\'s June 2025 switch from request-based to credit-based pricing produced surprise bills, backlash and a public apology with refunds ({{D1|We Are Founders, 2025}}). Anthropic imposed weekly caps on Claude Code from August 2025 after quietly tightening limits in July ({{D2|VentureBeat, 2025}}), and has had clustered multi-service outages affecting the API and Claude Code ({{D3|TechCrunch}}). Gartner predicts 40% of enterprises on consumption-priced coding tools will face costs at twice budget by 2027 ({{T2|Gartner via ArmorCode, 2025}}). Model lifecycles are vendor-controlled: OpenAI gives as little as two weeks\' notice before retiring preview models ({{D4|OpenAI docs}}), and Anthropic\'s retired models return errors on API calls ({{D5|Anthropic docs}}). Market concentration is high, with Anthropic at an estimated 54% of enterprise coding-LLM spend and OpenAI at 21% ({{D6|Menlo Ventures, 2025}}). The Windsurf episode shows the mechanism in action: Anthropic\'s withdrawal of Claude access from a competitor\'s product contributed to the collapse of OpenAI\'s acquisition and the break-up of the company ({{D7|TechCrunch, 2025}}). A secondary survey claims 81% of enterprise leaders worry about vendor dependency but only 6% believe they could switch without material disruption; we could not locate the primary and grade it Low ({{D8|Kusari, 2026}}).'));
add(h2('5.2 Partially documented: context files as critical infrastructure'));
add(p('Agent instruction files (CLAUDE.md, AGENTS.md, .cursorrules) have become a de facto architecture layer that agents read at session start; AGENTS.md alone is used by more than 60,000 open-source projects ({{M15|AGENTS.md standard}}). Anthropic reports using CLAUDE.md as the primary control mechanism for its own ~90% Claude-written codebase ({{M5|Cloud Native Now}}). Practitioners report that these files can be silently dropped from context in long sessions, after which agents violate written rules ({{D9|Spacelift}}); this is anecdotal. The point for H3 is that a codebase\'s operating manual is increasingly written for an agent rather than a person, and its portability depends on standards discussed in Section 7.'));
add(h2('5.3 Not documented: technical lock-in at the code level'));
add(p('The core of H3, that code produced by one model becomes harder for humans or for a different model to maintain, is asserted in vendor-comparison blogs and nowhere tested. No study measures whether AI-heavy codebases become harder for humans to modify without AI assistance, whether teams lose the ability to maintain code when they switch tools, or whether models exhibit style idioms that raise cross-model maintenance cost. The nearest evidence is indirect: the CodeScene finding that AI performs worse on unhealthy code (Section 4.3), the collapse in cross-file integration and long-term maintenance in GitClear\'s data (Section 4.1), and the finding that humans still perform 83% of maintenance on AI-generated files (Section 4.6). Those together describe a codebase drifting toward tool-only navigability without proving it.'));
add(p('**Verdict on H3.** Supported as economic and operational dependency; plausible but unevidenced as technical dependency. This is the largest single gap between the hypothesis and the literature.'));

// ---------- 6 Strategic direction ----------
add(h1('6. Strategic trend and direction'));
add(h2('6.1 Analyst forecasts: adoption with debt, not adoption without cost'));
add(p('Gartner\'s adoption forecast has been revised upward each year, from 75% of enterprise engineers using AI code assistants by 2028 (April 2024) to 90% (July 2025), against a base under 14% in early 2024 ({{T1|Gartner, 2025}}); a third figure of 70% circulates in vendor citations, and we treat "70-90% by 2028" as the safe claim. More pointed is Gartner\'s Predicts 2026, which forecasts a 2,500% increase in software defects by 2028 from prompt-to-app approaches, citing "a new class of defect" as AI generates context-deficient code that is syntactically correct but produces "complex architectural and logical bugs" harder to detect with traditional testing ({{T2|Gartner via ArmorCode, 2025}}). The primary report is paywalled; the figure is consistent across secondary citations and graded Medium. Gartner separately predicts over 40% of agentic AI projects will be cancelled by end-2027 for cost, unclear value and inadequate risk controls, a governance finding rather than a comprehension one ({{T3|Gartner, 2025}}). Forrester expects software development to be the top AI use case in 2026, moving from "vibe coding" to "vibe engineering" across the lifecycle, with 20% fewer computer-science enrolments and doubled time-to-fill for developer roles ({{T4|Forrester, 2025}}), and predicts 75% of technology leaders will face moderate-to-severe technical debt by 2026 ({{M25|InformationWeek}}). McKinsey puts existing technical debt at 20-40% of the value of a technology estate and reports that generative AI deliberately aimed at modernisation cut project durations 40-50% in its client work ({{T5|McKinsey}}), a reminder that the same tools can reduce debt when pointed at it.'));
add(h2('6.2 Vendor direction: from assistant to agent to fleets'));
add(p('Every vendor examined is converging on the same architecture: agents that own more of the lifecycle, orchestrated by humans in a supervisory role. GitHub\'s Agent HQ is a "mission control" for running agents from Anthropic, OpenAI, Google, Cognition and xAI inside one platform ({{T6|GitHub, 2025}}). Nadella frames Microsoft\'s strategy as moving "from building operating systems, devices for apps, to agents" ({{T8|9to5Mac, 2026}}). Anthropic exposes the Claude Code harness as an SDK and reports that Claude Code\'s annualised revenue grew from $1B in November 2025 to a reported $8B by May 2026 ({{D10|MindStudio, 2026}}), and Cursor reached a reported $60B valuation ({{D11|TheNextWeb, 2026}}); both are private-company figures. Google\'s Antigravity adds a "manager view" for orchestrating parallel agents ({{T9|ainoya.dev, 2025}}). AWS Kiro takes a distinct position: an agentic IDE that requires structured requirements and design before any code is generated ({{T7|AWS Kiro}}). Coding is the largest departmental AI spending category, at roughly $4B and 55% of departmental spend, with 76% of solutions bought rather than built ({{D6|Menlo Ventures, 2025}}).'));
add(h2('6.3 Three competing visions of what code is'));
add(p('The strategic question underneath H3 is whether code remains a human-owned artefact at all. Three positions are visible. The first, articulated by Karpathy as "Software 3.0", treats English as the programming language and code as a regenerable intermediate output ({{C14|Karpathy, 2025}}); Steve Yegge makes the operational version, that developers should stop reading code line by line and validate outcomes ({{C13|O\'Reilly, 2026}}); Charity Majors offers the more careful form, that software is bifurcating into disposable code that is regenerated and durable code that still needs trust built over years in production ({{C12|Majors, 2025}}). The second position, held by Thoughtworks, Kent Beck and the DORA programme, treats comprehension as preservable and prescribes engineering fundamentals: Beck\'s "augmented coding" keeps the human responsible for design, complexity and tests ({{C10|Beck, 2025}}), and Thoughtworks names cognitive debt and prescribes spec-driven development, mutation testing and provenance tracking rather than acceptance ({{C7|Thoughtworks, 2026}}). The third, hybrid position, embodied in Kiro and GitHub\'s Spec Kit, makes the specification and tests the durable human-owned artefact and treats code as compiled output ({{M14|Spec Kit guide}}). The evidence in Section 4 favours the second and third positions for durable systems: the observed debt is concentrated in exactly the architectural, cross-file layer that a regenerate-on-demand strategy would have to reconstruct each time.'));
add(h2('6.4 The labour pipeline'));
add(p('A second-order trend compounds H3 over a decade. Stanford\'s Digital Economy Lab, using ADP payroll data on 3.5-5 million workers per month, finds employment of 22-25-year-olds in the most AI-exposed occupations, including software development, about 19% below the counterfactual, driven by reduced hiring rather than layoffs, while workers aged 35-49 show no gap ({{T10|Brynjolfsson et al., 2026}}). Challenger, Gray & Christmas counted AI cited in 101,743 US job-cut announcements through June 2026, nearly double all of 2025, while cautioning that hiring is also up 25% ({{T11|Challenger, 2026}}); Meta, Microsoft, Salesforce and Oracle have all tied reductions to AI ({{T12|Founder Reports}}). The trial evidence that AI gains concentrate among juniors ({{E16|Cui et al., 2026}}) and that delegation harms skill formation ({{C1|Anthropic, 2026}}) closes the loop: the pipeline that turns juniors into the seniors who understand systems is narrowing at the moment the systems are becoming harder to understand.'));

// ---------- 7 Mitigations ----------
add(h1('7. Mitigations at the corporate level'));
add(p('Corporate responses are real, fast-moving and increasingly formal, but they lag the scale of adoption and none has published evidence of reducing downstream debt. We group them into eight classes.'));
add(h2('7.1 Governance stance and capability building'));
add(p('DORA\'s AI Capabilities Model prescribes seven organisational capabilities without which adoption amplifies dysfunction: a clear and communicated AI stance, healthy data ecosystems, AI-accessible internal data, strong version control, working in small batches, user-centric focus and quality internal platforms ({{M1|DORA, 2025}}). Thoughtworks places "complacency with AI-generated code" on Hold and recommends test-driven development, static analysis and explicit anti-automation-bias practice ({{M2|Thoughtworks}}). The largest producers, by contrast, have published adoption mandates rather than governance: Shopify made "reflexive AI usage a baseline expectation" tied to headcount and performance reviews ({{M3|Digital Commerce 360, 2025}}), and Meta set targets of 55% agent-assisted changes and made AI-driven impact a performance factor ({{M4|People Matters}}). Neither Google\'s 75% nor Anthropic\'s 80% statement is accompanied by published detail on how review, ownership or comprehension scales at that volume.'));
add(h2('7.2 Review discipline and quality gates'));
add(p('GitHub\'s guidance instructs reviewers to treat AI output as fallible, to watch for hallucinated APIs and silently deleted tests, and never to let AI review substitute for human review ({{M6|GitHub Docs}}). Amazon Q ships an automated review agent while AWS guidance still requires human sign-off policy ({{M7|AWS Docs}}). SonarQube\'s AI Code Assurance applies a stricter quality gate to agent-authored code before it can carry an assurance badge ({{M8|SonarSource}}). Anthropic reports an automated Claude reviewer that catches roughly a third of the bugs behind past incidents ({{P4|Anthropic, 2026}}). Enterprise guidance converges on CODEOWNERS-gated mandatory human sign-off for authentication, payments, infrastructure, migrations, public APIs and personal data, and warns of a new loophole: owners self-approving via AI review creates an incentive to "earn ownership" to bypass scrutiny ({{M9|CodeRabbit}}). The structural constraint is capacity: review is "a muscle with capacity limits", and AI volume risks breaking the knowledge feedback loop through which teams build shared understanding ({{C15|InfoQ, 2026}}). The UK NCSC\'s "vibe coding spectrum" is the most concrete government answer to this constraint, tying oversight intensity to code criticality: manual, high-oversight development for authentication, secrets, personal data and safety-critical code; full agent autonomy only for disposable prototypes ({{M21|NCSC, 2026}}).'));
add(h2('7.3 Provenance and attribution'));
add(p('Knowing which code an AI wrote is the precondition for every other control, and it is weak. Git "Co-authored-by" trailers are unenforced free text with no cryptographic binding, and a VS Code bug mis-attributed commits even with AI disabled ({{M10|AgentLair, 2026}}). SLSA and in-toto provide signed build provenance but no AI-specific extension in wide use ({{M11|SLSA}}); AI bills of materials remain proposals ({{M12|Palo Alto Networks}}). Thoughtworks lists Git AI, an open-source extension linking every AI-written line to the agent, model and prompt that produced it ({{M13|Thoughtworks}}). Until provenance captures autocomplete as well as agent PRs, longitudinal debt claims stay correlational.'));
add(h2('7.4 Spec-driven development and context files as documented architecture'));
add(p('The most direct response to comprehension debt is to make the specification, not the code, the durable artefact. GitHub Spec Kit and AWS Kiro make a written specification the thing agents plan and implement against, framed explicitly as a countermeasure to "undocumented, AI-generated software that works until someone needs to maintain it" ({{M14|Spec Kit guide}}); reported 3-10x first-pass gains are adopter-claimed and unverified. AGENTS.md, CLAUDE.md and Cursor rules files serve as a session-start architecture briefing that new human hires also read ({{M15|AGENTS.md}}).'));
add(h2('7.5 Limiting agent autonomy'));
add(p('Sandboxing and permission modes are the most mature control class. Claude Code\'s sandbox enforces filesystem and network boundaries at the operating-system level as an alternative to disabling permission checks ({{M18|Anthropic docs}}); GitHub\'s agent cannot push to default branches ({{P7|GitHub Docs}}). These address blast radius, the Replit and Gemini CLI failure mode, more than they address comprehension.'));
add(h2('7.6 Portability and anti-lock-in'));
add(p('The most concrete anti-dependency development is the Linux Foundation\'s Agentic AI Foundation, formed on 9 December 2025, into which OpenAI and Anthropic donated AGENTS.md and the Model Context Protocol and Block donated goose, with AWS, Google, Microsoft, Bloomberg and Cloudflare as platinum members, explicitly to keep agent standards open and interoperable ({{M16|Linux Foundation, 2025}}). Open-source harnesses such as Aider, Cline, OpenHands and Goose run against multiple model providers and are marketed as a hedge against single-vendor lock-in ({{M17|AvePoint, 2026}}). These standardise agent inputs (context files, tool protocols); nothing yet ensures that agent outputs remain comprehensible to humans or to a different model.'));
add(h2('7.7 Measurement'));
add(p('DX\'s AI Measurement Framework argues for measuring utilisation, impact and cost rather than acceptance rate or lines generated ({{M19|DX, 2025}}); DX\'s $720M acquisition by Atlassian suggests this view is being mainstreamed. GitHub\'s July 2026 Copilot dashboard segments users by adoption phase but still reports lines of code per day ({{M20|GitHub, 2026}}), a metric the debt evidence treats sceptically. No published measurement yet targets comprehension itself: how much of a codebase no current engineer can explain.'));
add(h2('7.8 Standards and regulation'));
add(p('Regulation currently governs the model supply chain more than the code it produces. ISO/IEC 42001 and NIST\'s AI RMF are general governance frameworks with an official crosswalk and no code-generation provisions ({{M23|NIST}}); NIST\'s generative-AI profile has no code-specific guidance ({{S14|NIST, 2024}}). Under the EU AI Act, coding assistants generally fall outside the high-risk annex ({{M24|Augment Code, 2026}}). The EU Cyber Resilience Act is the exception that bites: it makes manufacturers equally liable for AI-generated and human-written code, with reporting duties from September 2026 ({{S15|Sonar}}). In finance, FINOS\'s AI Governance Framework v2.0 adds runtime-enforceable agentic controls backed by Goldman Sachs and peers ({{M22|FINOS}}).'));
add(h3('Table 2. Mitigation classes, examples and what each addresses'));
add(table(['Class', 'Examples', 'Addresses', 'Evidence it works'], [
  ['Capability / stance', expand('{{M1|DORA 7 capabilities}}') + '; ' + expand('{{M2|Thoughtworks Hold}}'), 'Stability, amplification', 'Correlational (DORA)'],
  ['Review and gates', expand('{{M8|Sonar AI Code Assurance}}') + '; ' + expand('{{M9|CODEOWNERS sign-off}}') + '; ' + expand('{{M21|NCSC spectrum}}'), 'Defects, security, oversight', 'None published'],
  ['Provenance', expand('{{M13|Git AI}}') + '; ' + expand('{{M11|SLSA}}') + '; ' + expand('{{M12|AI-BOM}}'), 'Attribution, audit', 'Pre-standard'],
  ['Spec-driven / context files', expand('{{T7|Kiro}}') + '; ' + expand('{{M14|Spec Kit}}') + '; ' + expand('{{M15|AGENTS.md}}'), 'Comprehension, intent', 'Adopter claims only'],
  ['Autonomy limits', expand('{{M18|Sandboxing}}') + '; ' + expand('{{P7|no push to default}}'), 'Blast radius', 'Incident-driven'],
  ['Portability', expand('{{M16|Agentic AI Foundation}}') + '; ' + expand('{{M17|open harnesses}}'), 'Vendor lock-in (inputs)', 'Adoption counts'],
  ['Measurement', expand('{{M19|DX framework}}') + '; ' + expand('{{M20|Copilot dashboard}}'), 'Visibility', 'None on comprehension'],
  ['Regulation', expand('{{S15|EU CRA}}') + '; ' + expand('{{M22|FINOS v2}}') + '; ' + expand('{{M23|ISO 42001 / NIST}}'), 'Liability, security', 'Not yet in force / general'],
], [1900, 3600, 2000, 1860]));
add(caption('Sources in the companion claims table. "Evidence it works" records whether any published study shows the class reduces downstream debt.'));

// ---------- 8 Discussion ----------
add(h1('8. Discussion, limitations and recommendations'));
add(h2('8.1 Verdict on the hypothesis'));
add(p('The hypothesis is supported in its central mechanism and overstated in its framing. Production code is increasingly generated by agents, and the share receiving a substantive human read is falling at the aggregate level, even though individual developers report more scepticism, not less. The resulting debt is real and specific: it shows up as collapsed refactoring, rising duplication, isolated code that neither calls nor is called, persistent security flaws immune to model scale, and a negative relationship with delivery stability, while local code quality on isolated tasks is neutral or slightly improved. Comprehension loss is measured in one trial, admitted in developers\' own comments and visible in the failure of expertise metrics. Dependency is documented as pricing, rate limits, outages, model retirement and market concentration, but the claim that code itself becomes model-specific is untested. The framing should therefore shift from "code only models understand" to "code no one has read, in systems whose stability is degrading, maintained through tools whose terms the organisation does not control".'));
add(h2('8.2 Why the evidence looks contradictory'));
add(p('Three patterns explain the apparent conflicts. Vendor trials measure hours on isolated tasks, where duplication and legacy neglect cannot appear; longitudinal studies measure years on live repositories, where they dominate. Throughput and stability move in opposite directions, so studies that measure only one see only half the picture. And incentives run both ways: the pro-debt evidence comes largely from GitClear, Sonar, CodeScene, CodeRabbit and Faros, each of which sells a measurement of the problem, while the anti-debt evidence comes from GitHub, Microsoft-affiliated authors and Anthropic, each of which sells the tool. The cleanest sources, the AIDev studies, DORA and the independent randomised trials, sit in between, and they are the ones weighted highest here.'));
add(h2('8.3 Claims that did not survive verification'));
add(bullet('Uplevel\'s "41% more bugs" is gated; only "significantly higher bug rate" is confirmed ({{E22|Uplevel}}).'));
add(bullet('A "32.7% AI vs 84.4% human PR acceptance across 8.1 million PRs" figure in secondary blogs has no traceable primary and should not be used.'));
add(bullet('DORA 2024\'s exact 7.2% and 1.5% figures are taken from secondary coverage ({{E10|DORA 2024}}).'));
add(bullet('Gartner\'s 2,500% defect forecast and Cursor\'s 7% to 36.3% unreviewed-commit trend are consistent across secondary citations but unverified against primaries ({{T2|Gartner}}; {{P10|Cursor}}).'));
add(bullet('The "81% concerned, 6% able to switch" vendor-dependency survey and the "30% vs 90% task success with context files" figure lack primaries ({{D8|Kusari}}; {{M15|AGENTS.md}}).'));
add(bullet('METR\'s 19% slowdown has been superseded by its own authors ({{E15|METR 2026}}).'));
add(h2('8.4 Gaps for future research'));
add(numbered('**Maintenance cost over time.** Randomise AI assistance across teams and measure change cost, defect and incident rates on the same modules 12-24 months later. This experiment has not been run.'));
add(numbered('**Direct comprehension measurement.** Test whether developers can explain, debug and safely modify code an AI wrote for them versus code they wrote, longitudinally, in professional settings; the only trial is single-session with 52 participants.'));
add(numbered('**Harness lock-in.** Test whether AI-heavy codebases are harder for humans to modify without AI, and whether switching models raises maintenance cost. This is H3\'s core claim and is entirely unmeasured.'));
add(numbered('**Line-level provenance.** Record autocomplete as well as agent authorship natively so longitudinal claims can become attributional.'));
add(numbered('**Quality or neglect.** Join incident data to file provenance to resolve whether lower churn on AI files reflects quality or abandonment.'));
add(numbered('**Agentic versus autocomplete risk.** No security or quality study separates autonomous agents from line-level suggestions, which matters for the dependency framing.'));
add(numbered('**Mitigation efficacy.** No control in Section 7 has published evidence of reducing downstream debt.'));
add(h2('8.5 Recommendations for engineering organisations'));
add(numbered('**Tier oversight by criticality**, following the NCSC spectrum: full human review and ownership for authentication, secrets, data, payments and infrastructure; agent autonomy for disposable work.'));
add(numbered('**Measure the debt signature, not output.** Track refactoring share, duplication, cross-file integration and long-term maintenance rates alongside DORA stability metrics; treat lines of code per day and acceptance rate as exposure, not value.'));
add(numbered('**Make specifications and tests the durable artefact.** Adopt spec-driven workflows and keep AGENTS.md-class files under the same review as architecture documents, since they now are the architecture documentation.'));
add(numbered('**Record provenance now**, even imperfectly, so that future debt can be attributed; prefer tooling that links lines to agent, model and prompt.'));
add(numbered('**Design for the developer-level finding.** Delegated generation harms comprehension; conversational use does not. Require linear walkthroughs of agent output for durable code and use AI to explain legacy code as deliberately as to write new code.'));
add(numbered('**Hedge the vendor**: adopt open agent standards, keep at least one alternative model or harness exercised on the codebase, and budget for consumption-price volatility.'));
add(numbered('**Protect the pipeline.** Keep hiring and training juniors on comprehension tasks; the senior maintainers of 2035 are being hired, or not, now.'));

add(h1('9. Conclusion'));
add(p('AI-generated code is becoming a new form of technical debt, but not quite the form the hypothesis names. The evidence does not yet show code that only models understand; it shows code that no one has read, in volumes that outrun review, accumulating in systems whose delivery stability is measurably declining, with security flaws that model scaling has not reduced and comprehension effects that the one available trial finds large. The dependency is presently commercial and operational rather than technical, and it is being answered by portability standards for what agents read, not for what they write. The industry\'s direction, toward fleets of agents owning the lifecycle under human supervision, will amplify whichever of these outcomes an organisation\'s practices already favour. The decisive experiments, on maintenance cost over years and on whether humans can still change what agents wrote, remain to be run.'));

// ---------- References ----------
add(pageBreak());
add(h1('References'));
add(p('All 129 sourced claims, grouped by theme. Each entry gives the source title (hyperlinked), organisation, date, evidence type and grade. The same list, with the claim text and verification notes, is published as the companion claims table.', { align: AlignmentType.LEFT }));
const themes = [];
for (const c of claims) { const t = c.theme.split(':')[0]; if (!themes.includes(t)) themes.push(t); }
for (const t of themes) {
  add(h3(t));
  for (const c of claims.filter(x => x.theme.split(':')[0] === t)) {
    add(new Paragraph({
      children: H.runsFromMarkup(`${c.id}. [${c.source}](${c.url}). ${c.org}, ${c.date}. ${c.type}; grade ${c.strength}.`, { size: 19 }),
      spacing: { after: 80, line: 260 }, indent: { left: 360, hanging: 360 },
    }));
  }
}

// ---------- Appendix ----------
add(pageBreak());
add(h1('Appendix A. Research process and provenance'));
add(p('This paper was produced in a single orchestrated session. The hypothesis was decomposed into six research streams; a common instruction block fixed the citation, evidence-typing and counter-evidence rules; six subagents (one on a higher-capability model for the empirical stream, five on a faster model for the broader sweeps) ran in parallel with web search and page retrieval and wrote their findings to separate markdown files; the orchestrator read all six, re-verified the most load-bearing secondary figures against primary pages, and wrote this synthesis. The exact prompts, the raw stream outputs, the claims table as JSON and the script that generates this document are preserved in the repository alongside the paper, so any claim can be traced from paper to stream to source.', { align: AlignmentType.LEFT }));
add(p('Evidence grades: **High** means a peer-reviewed study, a large-sample survey with published methodology, a primary vendor document for a claim about that vendor, or a primary incident record. **Medium** means a vendor study with disclosed methodology, an analyst report reached through secondary coverage, or a credible practitioner analysis. **Low** means anecdotal reports or figures that could not be traced to a primary source. "Counter" marks evidence that weakens the hypothesis.', { align: AlignmentType.LEFT }));

// ---------- Document ----------
const doc = new Document({
  creator: 'Research synthesis',
  title: 'AI-Generated Code as the New Technical Debt',
  styles: {
    default: { document: { run: { font: H.FONT, size: 22 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 28, bold: true, font: H.FONT_SANS, color: '1F3864' }, paragraph: { spacing: { before: 360, after: 160 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 24, bold: true, font: H.FONT_SANS, color: '1F3864' }, paragraph: { spacing: { before: 280, after: 120 }, outlineLevel: 1 } },
      { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 22, bold: true, italics: true, font: H.FONT_SANS }, paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 2 } },
    ],
  },
  numbering: {
    config: [
      { reference: 'bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: 'numbers', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
    ],
  },
  features: { updateFields: true },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    headers: { default: new Header({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: 'AI-Generated Code as the New Technical Debt', font: H.FONT_SANS, size: 16, color: '666666' })] })] }) },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ children: ['Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES], font: H.FONT_SANS, size: 16, color: '666666' })] })] }) },
    children: body,
  }],
});

const out = path.join(__dirname, 'AI_Generated_Code_Technical_Debt.docx');
Packer.toBuffer(doc).then(buf => { fs.writeFileSync(out, buf); console.log('wrote', out, buf.length, 'bytes'); });
